HAI 1.2

I HAS A X ITZ 15
I HAS A Y ITZ 10

VISIBLE SUM OF X AN Y       BTW +
VISIBLE DIFF OF X AN Y      BTW -
VISIBLE PRODUKT OF X AN Y   BTW *
VISIBLE QUOSHUNT OF X AN Y  BTW /
VISIBLE MOD OF X AN Y       BTW modulo
VISIBLE BIGGR OF X AN Y     BTW max
VISIBLE SMALLR OF X AN Y    BTW min

KTHXBYE